# Generated by Django 5.2 on 2026-07-08 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0002_book_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="meta_keywords",
            field=models.TextField(blank=True),
        ),
    ]
