# Generated by Django 5.2 on 2026-07-09 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0003_book_meta_keywords"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="book",
            name="meta_keywords",
            field=models.TextField(),
        ),
    ]
