# Generated by Django 5.2 on 2026-07-09 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0004_alter_book_description_alter_book_meta_keywords"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="cover",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="pages",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="paper",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
