# Generated by Django 5.2 on 2026-07-06 17:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("subject", models.CharField(max_length=200)),
                ("preheader", models.CharField(blank=True, max_length=200)),
                ("html_body", models.TextField()),
                ("text_body", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("scheduled", "Scheduled"),
                            ("sending", "Sending"),
                            ("sent", "Sent"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="campaigns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Subscriber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("unsubscribed", "Unsubscribed"),
                            ("bounced", "Bounced"),
                            ("complained", "Complained"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("unsubscribed_at", models.DateTimeField(blank=True, null=True)),
                ("unsubscribe_reason", models.TextField(blank=True)),
                ("is_confirmed", models.BooleanField(default=False)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "confirmation_token",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("subscribed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="newsletter_subscriber",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmailEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("sent", "Sent"),
                            ("opened", "Opened"),
                            ("clicked", "Clicked"),
                            ("bounced", "Bounced"),
                            ("complained", "Complained"),
                            ("unsubscribed", "Unsubscribed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("occurred_at", models.DateTimeField(auto_now_add=True)),
                ("clicked_url", models.URLField(blank=True)),
                ("user_agent", models.TextField(blank=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="marketing.campaign",
                    ),
                ),
                (
                    "subscriber",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="marketing.subscriber",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="subscriber",
            index=models.Index(fields=["status"], name="marketing_s_status_317561_idx"),
        ),
        migrations.AddIndex(
            model_name="subscriber",
            index=models.Index(fields=["email"], name="marketing_s_email_7ce228_idx"),
        ),
        migrations.AddIndex(
            model_name="emailevent",
            index=models.Index(
                fields=["campaign", "event_type"], name="marketing_e_campaig_ba2fdc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emailevent",
            index=models.Index(
                fields=["subscriber", "event_type"],
                name="marketing_e_subscri_3c607d_idx",
            ),
        ),
    ]
