# Generated by Django 5.2 on 2026-07-07 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="emailevent",
            name="email_id",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
