# Generated by Django 5.2 on 2026-07-08 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketing", "0002_emailevent_email_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="campaign",
            name="scheduled_at",
        ),
        migrations.AlterField(
            model_name="campaign",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("ready", "Ready"),
                    ("sent", "Sent"),
                    ("cancelled", "Cancelled"),
                ],
                default="draft",
                max_length=20,
            ),
        ),
    ]
