# Generated by Django 5.2 on 2026-07-04 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0003_order_original_cart_order_stripe_pid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="original_cart",
        ),
        migrations.AddField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[("PD", "Pending"), ("IS", "Succeeded"), ("FL", "Failed")],
                default="PD",
                max_length=2,
            ),
        ),
    ]
