# Generated by Django 5.2 on 2026-07-05 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0004_remove_order_original_cart_order_payment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_status",
            field=models.CharField(
                choices=[
                    ("PD", "Pending"),
                    ("SH", "Shipped"),
                    ("PR", "Processing"),
                    ("RT", "Returned"),
                ],
                default="PD",
                max_length=2,
            ),
        ),
    ]
