# Generated by Django 5.2 on 2026-07-05 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0005_order_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_status",
            field=models.CharField(
                choices=[
                    ("PD", "Pending"),
                    ("SH", "Shipped"),
                    ("PR", "Processing"),
                    ("RT", "Returned"),
                    ("DR", "Delivered"),
                ],
                default="PD",
                max_length=2,
            ),
        ),
    ]
